2024-02-22 13:13:40,591 INFO    MainThread:16164 [wandb_setup.py:_flush():76] Configure stats pid to 16164
2024-02-22 13:13:40,592 INFO    MainThread:16164 [wandb_setup.py:_flush():76] Loading settings from C:\Users\amalj\.config\wandb\settings
2024-02-22 13:13:40,592 INFO    MainThread:16164 [wandb_setup.py:_flush():76] Loading settings from C:\Users\amalj\OneDrive\Desktop\lecture materials\S3\Research Project\Local Git Repo\Adversarial-MATL\Transfer learning in simple adversarial MPE env\wandb\settings
2024-02-22 13:13:40,592 INFO    MainThread:16164 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-22 13:13:40,592 INFO    MainThread:16164 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-22 13:13:40,592 INFO    MainThread:16164 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'Transfer learning in simple adversarial MPE env\\main.py', 'program': 'c:\\Users\\amalj\\OneDrive\\Desktop\\lecture materials\\S3\\Research Project\\Local Git Repo\\Adversarial-MATL\\Transfer learning in simple adversarial MPE env\\main.py'}
2024-02-22 13:13:40,594 INFO    MainThread:16164 [wandb_init.py:_log_setup():506] Logging user logs to C:\Users\amalj\OneDrive\Desktop\lecture materials\S3\Research Project\Local Git Repo\Adversarial-MATL\Transfer learning in simple adversarial MPE env\wandb\run-20240222_131340-9fn1jyau\logs\debug.log
2024-02-22 13:13:40,594 INFO    MainThread:16164 [wandb_init.py:_log_setup():507] Logging internal logs to C:\Users\amalj\OneDrive\Desktop\lecture materials\S3\Research Project\Local Git Repo\Adversarial-MATL\Transfer learning in simple adversarial MPE env\wandb\run-20240222_131340-9fn1jyau\logs\debug-internal.log
2024-02-22 13:13:40,594 INFO    MainThread:16164 [wandb_init.py:init():546] calling init triggers
2024-02-22 13:13:40,594 INFO    MainThread:16164 [wandb_init.py:init():552] wandb.init called with sweep_config: {}
config: {'write': True, 'render': 'human', 'seed': 5, 'save_interval': 10, 'eval_interval': 10, 'random_steps': 100, 'gamma': 0.99, 'lr': 0.0001, 'batch_size': 32, 'exp_noise': 1.0, 'obs_dim': 10, 'buffersize': 100000.0, 'target_freq': 100, 'hardtarget': True, 'action_dim': 5, 'anneal_frac': 200000.0, 'hidden': 100, 'train_freq': 1, 'good_agents_pretrain': 2, 'good_agents_transfer_train': 3, 'transfer_train': True, 'games': 100}
2024-02-22 13:13:40,594 INFO    MainThread:16164 [wandb_init.py:init():602] starting backend
2024-02-22 13:13:40,594 INFO    MainThread:16164 [wandb_init.py:init():606] setting up manager
2024-02-22 13:13:40,597 INFO    MainThread:16164 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn, using: spawn
2024-02-22 13:13:40,603 INFO    MainThread:16164 [wandb_init.py:init():613] backend started and connected
2024-02-22 13:13:40,608 INFO    MainThread:16164 [wandb_init.py:init():701] updated telemetry
2024-02-22 13:13:40,656 INFO    MainThread:16164 [wandb_init.py:init():741] communicating run to backend with 60.0 second timeout
2024-02-22 13:13:41,153 INFO    MainThread:16164 [wandb_run.py:_on_init():2131] communicating current version
2024-02-22 13:13:41,231 INFO    MainThread:16164 [wandb_run.py:_on_init():2140] got version response upgrade_message: "wandb version 0.16.3 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-02-22 13:13:41,231 INFO    MainThread:16164 [wandb_init.py:init():789] starting run threads in backend
2024-02-22 13:13:41,407 INFO    MainThread:16164 [wandb_run.py:_console_start():2112] atexit reg
2024-02-22 13:13:41,407 INFO    MainThread:16164 [wandb_run.py:_redirect():1967] redirect: SettingsConsole.WRAP_RAW
2024-02-22 13:13:41,407 INFO    MainThread:16164 [wandb_run.py:_redirect():2032] Wrapping output streams.
2024-02-22 13:13:41,407 INFO    MainThread:16164 [wandb_run.py:_redirect():2057] Redirects installed.
2024-02-22 13:13:41,408 INFO    MainThread:16164 [wandb_init.py:init():831] run started, returning control to user process
2024-02-22 13:13:47,381 WARNING MsgRouterThr:16164 [router.py:message_loop():77] message_loop has been closed
