episode: 0
episode 0 terminated at 100
Traceback (most recent call last):
  File "c:\Users\amalj\OneDrive\Desktop\lecture materials\S3\Research Project\Local Git Repo\Adversarial-MATL\Transfer learning in simple adversarial MPE env\main.py", line 138, in <module>
    main()
  File "c:\Users\amalj\OneDrive\Desktop\lecture materials\S3\Research Project\Local Git Repo\Adversarial-MATL\Transfer learning in simple adversarial MPE env\main.py", line 81, in main
    wandb.log({f'episode {j} terminated at global step {e}'})
  File "C:\Users\amalj\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 368, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\amalj\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 331, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Users\amalj\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 1712, in log
    self._log(data=data, step=step, commit=commit)
  File "C:\Users\amalj\anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 1489, in _log
    raise ValueError("wandb.log must be passed a dictionary")
ValueError: wandb.log must be passed a dictionary